# Site settings
name: 姚俊
location: 上海
company: 
position: Java开发工程师
github: https://github.com/
facebook: https://www.facebook.com/
phone: 1580424XXXX
email: xxxx@xxx.com

baseurl: "/"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

