# Site settings
name: 姚俊
location: 上海
company: 民映居
position: Java开发工程师
github: https://github.com/devil-yao
phone: 
email: devil.yao@hotmail.com
sex: 男
birth: 1995-02
school: 江苏理工学院
school_time: 2013-2017
profess: 计算机科学与技术

baseurl: "/"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

